cicd

diff --git a/cicd/cmd/run-all-with-config b/cicd/cmd/run-all-with-config
--- a/cicd/cmd/run-all-with-config
+++ b/cicd/cmd/run-all-with-config
@@ -22,6 +22,24 @@ context=$3
 profile=$4
 basedir=$5
 
+# download shell if it's not exists
+cmdpath=${basedir}/cicd/cmd
+which ${cmdpath}/dn-utils 2> /dev/null
+if [ $? -eq 1 ]; then
+	mkdir -p ${cmdpath} 2> /dev/null
+	wget -O ${cmdpath}/dn-utils https://happycloudpak.github.io/cicd-template/cmd/dn-utils
+	if [ $? -eq 1 ]; then
+		echo "CAN'T download ${cmdpath}/dn-utils"
+		exit 1
+	fi
+	chmod +x ${cmdpath}/dn-utils
+fi
+
+# download other shells and templates
+${cmdpath}/dn-utils cmd/build-image-with-config,cmd/clear-all-with-config,cmd/deploy-with-config,cmd/read-config,cmd/set-env ${cmdpath} 1
+${cmdpath}/dn-utils dockerfile/Dockerfile ${basedir}/cicd 0
+${cmdpath}/dn-utils deploy/deploy-with-config.yaml ${basedir}/cicd 0
+
 # build artifactory
 ${basedir}/mvnw clean package
 if [ $? -eq 1 ]; then exit 1; fi
